### PR TITLE
Basic support for store explorer

### PR DESCRIPTION
**Pull request by janicduplessis**
This is a super basic implementation of the store browser. It also supports search by id or type.

giphy

#### Caveats

It currently sends full store data on changes which potentially could be slow for very large stores or very frequent updates. Ideally we'd implement some sort of diffing to only send changes but that adds a lot of complexity to the bridge / store layer.

### CODE REVIEW

**Comment by sethwebster** [comment]
@janicduplessis - thanks so much for submitting this PR! Agreed that this would likely be very slow for large stores and internally, we have some very large stores as I suspect some folks using this early version do as well. 

We'll need to add some features to Relay to support a more scalable solution but this is something we have on our list, but not until (hopefully) later this year. We'll keep this open for now as not to lose track of it.

Thanks again for taking the time!

**Comment by leonardodino** [comment]
this could be an opt-in experimental feature, which would get replaced by the ideal implementation later on.
I think it can be useful 😄

**Comment by dadapoof** [comment]
@janicduplessis Thank you for the PR, I'm currently working on an extended store explorer based off of your PR that should land soon. Happy to review and merge improvements once that is committed. I'll close the PR for now but I'll comment here whenever I land the changes.

**Comment by janicduplessis** [comment]
@dadapoof Awesome!

**Comment by dadapoof** [comment]
Hi @janicduplessis, just following up here. A new version of the relay devtools extension was just released to the chrome store. This includes the store explorer as well as a bunch of cool new features. Check it out and let me know if you have any more issues seeing it!

**Comment by janicduplessis** [comment]
@dadapoof Great! Would it be possible to also publish `relay-devtools-core`. I'm using this in a flipper plugin I made (https://github.com/th3rdwave/flipper-plugin-relay-devtools). It is currently using the new code that was on master ~20 days ago, works great.

**Pull request closed without merging**
